In [11]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [12]:
data = pd.read_csv("data.csv")
data = data.drop(columns=["date","yr_built","yr_renovated","street","statezip","country","city","sqft_lot","sqft_above"],axis=1)
data.head()

,price,bedrooms,bathrooms,sqft_living,floors,waterfront,view,condition,sqft_basement
0,313000.0,3.0,1.50,1340,1.5,0,0,3,0
1,2384000.0,5.0,2.50,3650,2.0,0,4,5,280
2,342000.0,3.0,2.00,1930,1.0,0,0,4,0
3,420000.0,3.0,2.25,2000,1.0,0,0,4,1000
4,550000.0,4.0,2.50,1940,1.0,0,0,4,800

In [13]:
X = data.drop(columns=["price","waterfront"],axis=1)
y = data["price"]

ss =  StandardScaler()

X["sqft_living"] = ss.fit_transform(X[["sqft_living"]].values.reshape(-1,1))

In [14]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(" x train shape : ",x_train.shape)
x_train

 x train shape :  (3680, 7)

      bedrooms  bathrooms  sqft_living  floors  view  condition  sqft_basement
1898       4.0       2.50     0.654814     2.0     0          4              0
1370       4.0       3.00     1.641210     2.0     0          3              0
3038       4.0       2.50     0.696347     2.0     0          3              0
2361       4.0       3.75     1.963087     2.0     0          3              0
156        3.0       2.00    -0.144686     2.0     0          3              0
...        ...        ...          ...     ...   ...        ...            ...
4426       3.0       1.00    -0.996101     1.5     0          3              0
466        4.0       2.00     0.395236     1.0     0          3           1120
3092       3.0       1.00    -1.027250     1.0     0          4            160
3772       2.0       1.00    -1.276445     1.5     0          3              0
860        2.0       1.00    -0.674224     1.0     0          3            630

[3680 rows x 7 columns]

In [15]:
model = RandomForestRegressor()
model.fit(x_train,y_train)

RandomForestRegressor()

In [16]:
model.feature_importances_

array([0.04049049, 0.0849374 , 0.65573698, 0.03306303, 0.04703863,
       0.0357489 , 0.10298457])

In [17]:
pred  =  model.predict(x_test)

In [18]:
model.score(X,y)

0.33910887363155406

In [19]:
mean_absolute_percentage_error(y_test,pred)

3.708098025541451e+19

In [21]:
import pickle ,joblib

with open("models/model.pkl","wb") as f:
    pickle.dump(model,f)
    

joblib.dump(ss, 'models/std_scaler.bin', compress=True)

['models/std_scaler.bin']